### ISSUE TITLE
Feature request, all command in non-interactive mode.

### ISSUE THREAD

**Issue by devosalain** [freebsd/poudriere#879] opened 2021-06-15 19:11 UTC
When you remove a ports you must aknowledge with yes even if it is unregistering.
Example:
poudriere ports -k -d  -p $PORTS

This is annoyend for scripting. Default yes or no would be a nice feature to have.

**Comment by bdrewery** [comment] 2021-08-03 17:29
Dupe of #592

**Closed by bdrewery** 2021-08-03 17:29 UTC
