### ISSUE TITLE
testport -o is  weird

### ISSUE THREAD

**Issue by jmmv** [freebsd/poudriere#338] opened 2015-08-13 11:39 UTC
Today I had to play with `testport` to debug a port breakage. First of all `testport -i` is awesome (although it took me a while to figure this out because the name of the command didn't map my mental model of what I wanted to do.)

However, the point of this bug is to mention that the `testport -o origin` syntax is very strange. The reason is that `bulk` takes a list of ports in the form `category/port` as positional arguments without any flag... yet `testport` requires `-o` for some odd reason. Flags are often used to represent optional values, but in this case `-o` is not optional at all which in turn made things more confusing.

I do not know the reasons behind having a `-o` flag to represent the port to debug, nor I do not know why such flag is called "origin" instead of port name. There may be some historical reasons for this.

My suggestion would be to drop the `-o` flag from `testport` altogether and just accept the port to debug in `category/port` form as the only positional argument to the command.

(Issue #180 is related to this regarding the lack of symmetry between `testport` and `bulk`.)

**Comment by bdrewery** [comment] 2015-08-13 17:56
"origin" is the proper name in the context of ports.

This bug likely is a duplicate of another. It's been requested before to make the -o optional. I'm not against doing so.

**Comment by bdrewery** [comment] 2015-10-22 17:43
I've made -o optional. So now there's really no need to use it or add it to bulk!

**Closed by bdrewery** 2015-10-22 17:43 UTC
