### ISSUE TITLE
[feature] Testing and QA: regression-test & TEST_DEPENDS support

### ISSUE THREAD

**Issue by bapt** [freebsd/poudriere#55] opened 2014-09-18 15:40 UTC
Requesting the addition of two QA and testing related features:

1) regression-test: target support

2) TEST_DEPENDS support

As far as I'm aware, later tinderbox versions support (1) and redports supported the latter (2)

Adding these features to our most popular build tools may also encourage support to be added to the FreeBSD ports framework as well.

**Comment by saper** [comment] 2018-03-16 20:14
I think it is called `TEST_TARGET` today... would be great to run automated tests after build.

**Comment by bdrewery** [comment] 2018-03-16 20:16
Duplicate of #355

**Closed by bdrewery** 2018-03-16 20:16 UTC
Labels: Feature_Request, Imported
