### ISSUE TITLE
poudriere-devel testport check-sanity fails

### ISSUE THREAD

**Issue by lifanov** [freebsd/poudriere#451] opened 2017-03-02 17:36 UTC
Hi!
The latest poudriere-devel port fails testport actions with this:
[00:00:20] ====>> Error: Build failed in phase: check-sanity

To reproduce, run testport on, say, databases/libzdb.

**Comment by bdrewery** [comment] 2017-03-06 22:16
What is the error from the log for databases/libzdb?

**Comment by bdrewery** [comment] 2017-03-06 22:34
I can't reproduce this on the lastest master, which I am about to update poudriere-devel with.  This seems like it would be a ports problem though.

**Comment by lifanov** [comment] 2017-03-06 23:05
```
$ sudo poudriere testport -z test -p lifanov -j 103amd64 -o databases/libzdb   
[00:00:00] ====>> Creating the reference jail... done
[00:00:02] ====>> Mounting system devices for 103amd64-lifanov-test
[00:00:02] ====>> Mounting ports/packages/distfiles
[00:00:02] ====>> Stashing existing package repository
[00:00:02] ====>> Mounting packages from: /var/poudriere/data/packages/103amd64-lifanov-test
/etc/resolv.conf -> /var/poudriere/data/.m/103amd64-lifanov-test/ref/etc/resolv.conf
[00:00:02] ====>> Starting jail 103amd64-lifanov-test
[00:00:02] ====>> Logs: /var/poudriere/data/logs/bulk/103amd64-lifanov-test/2017-03-06_18h04m13s
[00:00:02] ====>> WWW: http://10.10.0.1:8000//build.html?mastername=103amd64-lifanov-test&build=2017-03-06_18h04m13s
[00:00:02] ====>> Loading MOVED
[00:00:02] ====>> Calculating ports order and dependencies
[00:00:03] ====>> Sanity checking the repository
[00:00:03] ====>> Checking packages for incremental rebuild needed
[00:00:04] ====>> Deleting stale symlinks
[00:00:04] ====>> Deleting empty directories
[00:00:04] ====>> Cleaning the build queue
[00:00:05] ====>> Recording filesystem state for prepkg... done
[00:00:05] ====>> Committing packages to repository
[00:00:05] ====>> Removing old packages
[00:00:05] ====>> Building with flags: 
[00:00:05] ====>> Removing existing /usr/local
build started at Mon Mar  6 18:04:18 EST 2017
port directory: /usr/ports/databases/libzdb
building for: FreeBSD pkg.lifanov.com 10.3-RELEASE-p5 FreeBSD 10.3-RELEASE-p5 amd64
maintained by: ports@FreeBSD.org
Makefile ident:      $FreeBSD: head/databases/libzdb/Makefile 419869 2016-08-08 17:40:33Z pi $
Poudriere version: 3.2-pre
Host OSVERSION: 1200023
Jail OSVERSION: 1003000
Job Id: 

---Begin Environment---
PKGREPOSITORY=/tmp/pkgs
PACKAGES=/tmp/pkgs
SHELL=/bin/csh
OSVERSION=1003000
UNAME_v=FreeBSD 10.3-RELEASE-p5
UNAME_r=10.3-RELEASE-p5
BLOCKSIZE=K
MAIL=/var/mail/root
STATUS=1
SAVED_TERM=xterm-256color
NO_WARNING_PKG_INSTALL_EOL=yes
MASTERMNT=/var/poudriere/data/.m/103amd64-lifanov-test/ref
UID=0
FORCE_PACKAGE=yes
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin
POUDRIERE_BUILD_TYPE=bulk
OLDPWD=/var/poudriere/data/.m/103amd64-lifanov-test/ref/.p
PWD=/
MASTERNAME=103amd64-lifanov-test
SCRIPTPREFIX=/usr/local/share/poudriere
USER=root
HOME=/root
POUDRIERE_VERSION=3.2-pre
SCRIPTPATH=/usr/local/share/poudriere/testport.sh
GID=0
TRYBROKEN=yes
LIBEXECPREFIX=/usr/local/libexec/poudriere
LOCALBASE=/usr/local
PACKAGE_BUILDING=yes
---End Environment---

---Begin OPTIONS List---
===> The following configuration options are available for libzdb-3.1_1:
     SSL=on: SSL protocol support
====> Options available for the multi DB: you have to choose at least one of them
     MYSQL=on: MySQL database support
     PGSQL=on: PostgreSQL database support
     SQLITE=on: SQLite database support
===> Use 'make config' to modify these settings
---End OPTIONS List---

--CONFIGURE_ARGS--
--enable-openssl=/usr --with-mysql=/usr/local/bin/mysql_config --with-postgresql=/usr/local/bin/pg_config --with-sqlite=/usr/local --prefix=/usr/local ${_LATE_CONFIGURE_ARGS}
--End CONFIGURE_ARGS--

--CONFIGURE_ENV--
MAKE=gmake XDG_DATA_HOME=/wrkdirs/usr/ports/databases/libzdb/work  XDG_CONFIG_HOME=/wrkdirs/usr/ports/databases/libzdb/work  HOME=/wrkdirs/usr/ports/databases/libzdb/work TMPDIR="/tmp" SHELL=/bin/sh CONFIG_SHELL=/bin/sh CONFIG_SITE=/usr/ports/Templates/config.site lt_cv_sys_max_cmd_len=262144
--End CONFIGURE_ENV--

--MAKE_ENV--
OPENSSLBASE=/usr OPENSSLDIR=/etc/ssl OPENSSLINC=/usr/include OPENSSLLIB=/usr/lib XDG_DATA_HOME=/wrkdirs/usr/ports/databases/libzdb/work  XDG_CONFIG_HOME=/wrkdirs/usr/ports/databases/libzdb/work  HOME=/wrkdirs/usr/ports/databases/libzdb/work TMPDIR="/tmp" NO_PIE=yes WITHOUT_DEBUG_FILES=yes WITHOUT_KERNEL_SYMBOLS=yes SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  LIBDIR="/usr/lib"  CC="cc" CFLAGS="-O2 -pipe  -fstack-protector -fno-strict-aliasing"  CPP="cpp" CPPFLAGS="-I/usr/local/include -I/usr/local/include"  LDFLAGS=" -L/usr/local/lib -pthread  -L/usr/local/lib -fstack-protector" LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fstack-protector -fno-strict-aliasing "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 444"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444"
--End MAKE_ENV--

--PLIST_SUB--
OSREL=10.3
PREFIX=%D
LOCALBASE=/usr/local
RESETPREFIX=/usr/local
PORTDOCS=""
PORTEXAMPLES=""
LIB32DIR=lib
DOCSDIR="share/doc/libzdb"
EXAMPLESDIR="share/examples/libzdb"
DATADIR="share/libzdb"
WWWDIR="www/libzdb"
ETCDIR="etc/libzdb"
--End PLIST_SUB--

--SUB_LIST--
PREFIX=/usr/local
LOCALBASE=/usr/local
DATADIR=/usr/local/share/libzdb
DOCSDIR=/usr/local/share/doc/libzdb
EXAMPLESDIR=/usr/local/share/examples/libzdb
WWWDIR=/usr/local/www/libzdb
ETCDIR=/usr/local/etc/libzdb
--End SUB_LIST--

---Begin make.conf---
USE_PACKAGE_DEPENDS=yes
BATCH=yes
WRKDIRPREFIX=/wrkdirs
PORTSDIR=/usr/ports
PACKAGES=/packages
DISTDIR=/distfiles
#### /usr/ports/Mk/Scripts/ports_env.sh ####
ARCH=amd64
CONFIGURE_MAX_CMD_LEN=262144
HAVE_COMPAT_IA32_KERN=YES
OPSYS=FreeBSD
OSREL=10.3
OSVERSION=1003000
PYTHONBASE=/usr/local
_JAVA_OS_LIST_REGEXP=native\|linux
_JAVA_VENDOR_LIST_REGEXP=openjdk\|oracle\|sun
_JAVA_VERSION_LIST_REGEXP=1.6\|1.7\|1.8\|1.6+\|1.7+\|1.8+
_OSRELEASE=10.3-RELEASE-p5
_SMP_CPUS=12
#### Misc Poudriere ####
---End make.conf---
--Resource limits--
cpu time               (seconds, -t)  unlimited
file size           (512-blocks, -f)  unlimited
data seg size           (kbytes, -d)  33554432
stack size              (kbytes, -s)  524288
core file size      (512-blocks, -c)  unlimited
max memory size         (kbytes, -m)  unlimited
locked memory           (kbytes, -l)  64
max user processes              (-u)  89999
open files                      (-n)  1024
virtual mem size        (kbytes, -v)  unlimited
swap limit              (kbytes, -w)  unlimited
socket buffer size       (bytes, -b)  unlimited
pseudo-terminals                (-p)  unlimited
kqueues                         (-k)  unlimited
umtx shared locks               (-o)  unlimited
--End resource limits--
=======================<phase: check-sanity   >============================
make: "/usr/ports/Mk/bsd.port.mk" line 1446: Cannot open /usr/ports/Mk/Uses/mysql.mk
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/ports/databases/libzdb
build of databases/libzdb ended at Mon Mar  6 18:04:19 EST 2017
build time: 00:00:01
!!! build failure encountered !!!
[00:00:05] ====>> Error: Build failed in phase: check-sanity
[00:00:05] ====>> Cleaning up
103amd64-lifanov-test: removed
103amd64-lifanov-test-n: removed
[00:00:05] ====>> Unmounting file systems
```

**Comment by lifanov** [comment] 2017-03-06 23:06
This is vanilla 10.3-RELEASE jail on a vanilla ports tree on poudriere-devel-3.1.99.20170221_1.
This is while poudriere-3.1.14_3 works with no issue.

**Comment by bdrewery** [comment] 2017-03-07 01:14
```
make: "/usr/ports/Mk/bsd.port.mk" line 1446: Cannot open /usr/ports/Mk/Uses/mysql.mk
```

This is some local problem.

Double check the path from this for a Mk/Uses/mysql.mk file: `poudriere ports -l|awk '$1 == "lifanov"'`

**Comment by lifanov** [comment] 2017-03-07 15:07
```
$ file $(poudriere ports -l|awk '$1 == "lifanov"'|cut -w -f3)/Mk/Uses/mysql.mk
/usr/home/lifanov/src/svn/freebsd/ports/head/Mk/Uses/mysql.mk: ASCII text
```
This works perfectly in non-devel version of poudriere.
I tried advanced interactive mode (-I) and it works in both poudriere and poudriere-devel after I manually "cd /usr/ports/databases/libzdb" and run "make check-sanity" and "make stage-qa".

**Comment by lifanov** [comment] 2017-03-07 17:42
I just updated to poudriere-devel-3.1.99.20170306 and I can still reproduce the problem.
I tried the same thing with default tree (created with "poudriere ports -c -m svn" and no other arguments), and I get a different error:

```
[00:00:06] ====>> Loading MOVED
[00:00:07] ====>> Gathering ports metadata
[00:00:09] ====>> Calculating ports order and dependencies
[00:00:10] ====>> pkg package missing, skipping sanity
[00:00:10] ====>> Skipping incremental rebuild and repository sanity checks
[00:00:10] ====>> Cleaning the build queue
[00:00:10] ====>> Recording filesystem state for prepkg...mtree: proc: Not a directory
[00:00:11] ====>> Cleaning up
103amd64-default-test: removed
103amd64-default-test-n: removed
```

**Comment by bdrewery** [comment] 2017-03-07 17:52
Do you have a local nullfs or tmpfs or unionfs mount over your /usr/home/lifanov/src/svn/freebsd/ports/head/Mk or /usr/home/lifanov/src/svn/freebsd/ports/head/Mk/Uses directory?

I've had the mtree report previously as well but haven't had a chance to look into it.

**Comment by lifanov** [comment] 2017-03-07 18:02
No, it's one giant filesystem:
$ df -m /usr/home/lifanov/src/svn/freebsd/ports                                
Filesystem         1M-blocks   Used   Avail Capacity  Mounted on
tank/DATA/usr.home   2174449 519906 1654542    24%    /usr/home

**Comment by bdrewery** [comment] 2017-03-07 18:13
Weird. I'm on mobile now so not sure if you did this already. On the portsree not giving proc error, or set USE_PROCFS=yes for now (spelling might be wrong), Can you try a testport -i and then after the check-sanity failure do an ls -al in Mk/ and Mk/Uses and check the contend of mysql.mk?

The error is very odd.

Also check a simple test like testport ports-mgmt/pkg.

Thanks!

Regards,
Bryan Drewery

**Comment by bdrewery** [comment] 2017-03-07 18:32
What kernel branch and revision?

Regards,
Bryan Drewery

**Comment by mat813** [comment] 2017-03-07 19:59
I'd bet /usr/home/lifanov/src/svn/freebsd/ports/head/Mk/Uses/mysql.mk has a mode of 600 (because you used svn patch) (though shall never, ever, use svn patch)

**Comment by bdrewery** [comment] 2017-03-07 20:02
And BUILD_AS_NON_ROOT is not able to access it.  -devel has that on by default and 3.1 is off by default.

**Comment by lifanov** [comment] 2017-03-07 21:23
Yep! You are totally right!
I use "svn patch" all the time and mysql.mk was mode 600. I changed it to 644 and now testport works.

**Comment by mat813** [comment] 2017-03-07 21:29
Never ever use svn patch, it uses some brain damaged code from apr, and messes up every file modes. (Or always think to do a chmod a+rX afterwards, so, as you'll forget, never use svn patch.)

**Comment by bdrewery** [comment] 2017-03-07 21:30
The mtree issue is fixed in master and soon poudriere-devel. Closing. Thanks for your reports!

**Closed by bdrewery** 2017-03-07 21:30 UTC
