### ISSUE TITLE
bulk fails with "don't know how to make check-sanity"

### ISSUE THREAD

**Issue by adriaandegroot** [freebsd/poudriere#640] opened 2018-09-08 09:07 UTC
Building a port (today, x11/sddm) with poudriere fails with an error message from poudriere like:

```
[00:00:05] [01] [00:00:01] Finished x11/sddm | sddm-0.17.0: Failed: check-sanity
```

and the log file of that build says

```
=======================<phase: check-sanity   >============================
make: don't know how to make check-sanity. Stop

make: stopped in /usr/ports/x11/sddm
=>> Cleaning up wrkdir
```

This also happens with some other ports as well, but seems random. Other ports build in the same *bulk* run do check-sanity.

(filing this issue so that it's easier to search for "poudriere check-sanity fails")

**Comment by adriaandegroot** [comment] 2018-09-08 09:09
From #584, from @bdrewery and confirmed by @yasuhirokimura (and by me as well):

> The problem is that your Makefile has bad permissions. Poudriere in 3.2 now builds several phases for the port as not root. This particular error can happen if the Makefile is not readable by world.

As of 3.2.7 the error message is still confusing, but the solution is straightforward: `chmod go+r Makefile` on the affected port (possibly also other files in the affected port directory).

**Comment by bdrewery** [comment] 2019-02-22 23:35
Closing duplicate of #584

**Closed by bdrewery** 2019-02-22 23:35 UTC
