### ISSUE TITLE
"poudriere options -c" not invoking dialog4ports

### ISSUE THREAD

**Issue by CoryAlbrecht** [freebsd/poudriere#737] opened 2020-01-03 22:03 UTC
So went to do do my quarterly packages update for  my FreeBSD servers and I had a problem updating  www/nextcloud because www/apache24 was getting skipped because security/distcache  was bot being built.

When I ran "poudriere options -c -j jailname -p portsname www/apache24" to turn off SOCACHE_DC, it didn't invoke dialog4ports to let me change the options.

I saved everything in /usr/local/etc/poudriere.d then deleted the jails and ports trees used by poudriere and recreated them. Same problem, dialog4ports not getting invoked.

So I went and looked in the directories where jails are kept and could not find dialog4ports anywhere underneath /usr/local/poudiere/jails/jailname.

Why is that not there? Aren't port options set by running 'make config' inside the jail?

It this point I am unable to change options for any port in any new jail of any version.

The machine running poudriere is 12.0-RELEASE-p11 and poudriere is 3.3.2_1 installed with pkg.

**Comment by CoryAlbrecht** [comment] 2020-02-23 15:15
bump

**Comment by CoryAlbrecht** [comment] 2020-03-09 00:57
bump

**Comment by bdrewery** [comment] 2020-04-08 20:36
It works for me. What error did you get?

**Comment by CoryAlbrecht** [comment] 2020-04-10 19:29
No errors. It simply did not run dialog4ports to change options.

**Comment by bdrewery** [comment] 2020-04-10 19:30
You have it installed in the host?

**Comment by bdrewery** [comment] 2021-04-28 18:07
Dupe of #599

**Closed by bdrewery** 2021-04-28 18:07 UTC
