### ISSUE TITLE
rm -x on stable/9

### ISSUE THREAD

**Issue by kostikbel** [freebsd/poudriere#366] opened 2015-11-30 14:28 UTC
Machine is running
FreeBSD tom.home 9.3-STABLE FreeBSD 9.3-STABLE #9 r290391: Thu Nov  5 15:05:58 EET 2015     root@tom.home:/usr/obj/usr/home/bsd/src/sys/TOM  amd64

Poudriere 3.1.10 installed from ports, barfs:
```
[00:08:48] ====>> Deleting stale symlinks
[00:08:48] ====>> Deleting empty directories
[00:08:48] ====>> Cleaning the build queue
[00:08:49] ====>> Recording filesystem state for prepkg... done
[00:08:53] ====>> Building 19 packages using 1 builders
[00:08:53] ====>> Starting/Cloning builders
rm: illegal option -- x
usage: rm [-f | -i] [-dIPRrvW] file ...
       unlink file
[00:08:53] ====>> Cleaning up
rm: illegal option -- x
usage: rm [-f | -i] [-dIPRrvW] file ...
       unlink file
[00:08:53] ====>> Umounting file systems
rm: illegal option -- x
usage: rm [-f | -i] [-dIPRrvW] file ...
       unlink file
rm: illegal option -- x
usage: rm [-f | -i] [-dIPRrvW] file ...
       unlink file
```

**Comment by brd** [comment] 2015-11-30 14:31
Duplicate of #365

**Closed by brd** 2015-11-30 14:31 UTC

**Comment by bdrewery** [comment] 2015-11-30 17:27
Fix committed to ports.
