### ISSUE TITLE
ghostscript9-agpl-base-9.16_5.txz repeatedly deleted for changed options

### ISSUE THREAD

**Issue by reezer** [freebsd/poudriere#543] opened 2017-11-12 09:49 UTC
After updating to 3.2 poudriere started repeatedly reporting changed options for ghostscript9-agpl-base-9.16_5.txz.

This is despite building successfully and a new repository being built.

This package has a lot of GS_* options, so I will not put the lines here. However, after diffing I see that the only detected change is adding `GS_cups`.

The make.conf used in this build includes `OPTIONS_UNSET+=CUPS`, which might explain why GS_cups isn't found in the current build, but doesn't explain why it would still be adding this option.

Could it be related to both [a GS_cups and a CUPS option existing in the port](https://www.freshports.org/print/ghostscript9-agpl-base/)?

EDIT: Adding `GS_cups` to `OPTIONS_UNSET` works around this issue.

**Comment by bdrewery** [comment] 2017-11-13 19:35
Can you show a log of the rebuild issue please?

**Comment by brd** [comment] 2017-11-13 19:45
```[00:00:00] Loading MOVED
[00:00:00] Ports supports: DEPENDS_ARGS SELECTED_OPTIONS
[00:00:00] Gathering ports metadata
[00:00:03] Calculating ports order and dependencies
[00:00:04] Sanity checking the repository
[00:00:04] Checking packages for incremental rebuild needs
[00:00:04] Deleting ghostscript9-agpl-base-9.16_5.txz: changed options
[00:00:05] Deleting ghostscript9-agpl-base-9.16_5.txz: changed options                                                                                      
[00:00:05] Pkg: DOCS GS_alc1900 GS_alc2000 GS_alc4000 GS_alc4100 GS_alc8500 GS_alc8600 GS_ap3250 GS_appledmp GS_atx23 GS_atx24 GS_atx38 GS_bbox GS_bit GS_bi
tcmyk GS_bitrgb GS_bj10e GS_bj10v GS_bj10vh GS_bj200 GS_bjc600 GS_bjc800 GS_bjc880j GS_bjccmyk GS_bjccolor GS_bjcgray GS_bjcmono GS_bmp16 GS_bmp16m GS_bmp25
6 GS_bmp32b GS_bmpgray GS_bmpmono GS_bmpsep1 GS_bmpsep8 GS_ccr GS_cdeskjet GS_cdj1600 GS_cdj500 GS_cdj550 GS_cdj670 GS_cdj850 GS_cdj880 GS_cdj890 GS_cdj970 
GS_cdjcolor GS_cdjmono GS_cdnj500 GS_cfax GS_chp2200 GS_cif GS_cljet5 GS_cljet5c GS_cljet5pr GS_coslw2p GS_coslwxl GS_cp50 GS_declj250 GS_deskjet GS_devicen
 GS_dfaxhigh GS_dfaxlow GS_display GS_dj505j GS_djet500 GS_djet500c GS_dl2100 GS_dmprt GS_dnj650c GS_epag GS_epl2050 GS_epl2050p GS_epl2120 GS_epl2500 GS_ep
l2750 GS_epl5800 GS_epl5900 GS_epl6100 GS_eplcolor GS_eplmono GS_eps2write GS_eps9high GS_eps9mid GS_epson GS_epsonc GS_escpage GS_faxg3 GS_faxg32d GS_faxg4
 GS_fmlbp GS_fmpr GS_fs600 GS_gdi GS_hl1240 GS_hl1250 GS_hl7x0 GS_ibmpro GS_ijs GS_imagen GS_inferno GS_inkcov GS_iwhi GS_iwlo GS_iwlq GS_jetp3852 GS_jj100 
GS_jpeg GS_jpeggray GS_la50 GS_la70 GS_la75 GS_la75plus GS_laserjet GS_lbp310 GS_lbp320 GS_lbp8 GS_lex2050 GS_lex3200 GS_lex5700 GS_lex7000 GS_lips2p GS_lip
s3 GS_lips4 GS_lips4v GS_lj250 GS_lj4dith GS_lj4dithp GS_lj5gray GS_lj5mono GS_ljet2p GS_ljet3 GS_ljet3d GS_ljet4 GS_ljet4d GS_ljet4pjl GS_ljetplus GS_ln03 
GS_lp1800 GS_lp1900 GS_lp2000 GS_lp2200 GS_lp2400 GS_lp2500 GS_lp2563 GS_lp3000c GS_lp7500 GS_lp7700 GS_lp7900 GS_lp8000 GS_lp8000c GS_lp8100 GS_lp8200c GS_
lp8300c GS_lp8300f GS_lp8400f GS_lp8500c GS_lp8600 GS_lp8600f GS_lp8700 GS_lp8800c GS_lp8900 GS_lp9000b GS_lp9000c GS_lp9100 GS_lp9300 GS_lp9400 GS_lp9500c 
GS_lp9600 GS_lp9600s GS_lp9800c GS_lq850 GS_lvga256 GS_lxm3200 GS_lxm5700m GS_m8510 GS_mag16 GS_mag256 GS_md1xMono GS_md2k GS_md50Eco GS_md50Mono GS_md5k GS
_mgr4 GS_mgr8 GS_mgrgray2 GS_mgrgray4 GS_mgrgray8 GS_mgrmono GS_miff24 GS_mj500c GS_mj6000c GS_mj700v2c GS_mj8000c GS_ml600 GS_necp6 GS_npdl GS_oce9050 GS_o
ki182 GS_oki4w GS_okiibm GS_omni GS_oprp GS_opvp GS_paintjet GS_pam GS_pbm GS_pbmraw GS_pcl3 GS_pcx16 GS_pcx24b GS_pcx256 GS_pcxcmyk GS_pcxgray GS_pcxmono G
S_pdfwrite GS_perm GS_pgm GS_pgmraw GS_pgnm GS_pgnmraw GS_photoex GS_picty180 GS_pj GS_pjetxl GS_pjxl GS_pjxl300 GS_pkm GS_pkmraw GS_pksm GS_pksmraw GS_plan
 GS_plan9bm GS_planc GS_plang GS_plank GS_planm GS_plib GS_plibc GS_plibg GS_plibk GS_plibm GS_png16 GS_png16m GS_png256 GS_pngalpha GS_pnggray GS_pngmono G
S_pnm GS_pnmraw GS_ppm GS_ppmraw GS_pr1000 GS_pr1000_4 GS_pr150 GS_pr201 GS_ps2write GS_psdcmyk GS_psdrgb GS_pxlcolor GS_pxlmono GS_r4081 GS_rpdl GS_sgirgb
GS_sj48 GS_spotcmyk GS_st800 GS_stcolor GS_sunhmono GS_t4693d2 GS_t4693d4 GS_t4693d8 GS_tek4696 GS_tiff12nc GS_tiff24nc GS_tiff32nc GS_tiffcrle GS_tiffg3 GS
_tiffg32d GS_tiffg4 GS_tiffgray GS_tifflzw GS_tiffpack GS_tiffsep GS_uniprint GS_vgalib GS_xcf GS_xcfcmyk GS_xes ICONV
[00:00:05] New: DOCS GS_alc1900 GS_alc2000 GS_alc4000 GS_alc4100 GS_alc8500 GS_alc8600 GS_ap3250 GS_appledmp GS_atx23 GS_atx24 GS_atx38 GS_bbox GS_bit GS_bi
tcmyk GS_bitrgb GS_bj10e GS_bj10v GS_bj10vh GS_bj200 GS_bjc600 GS_bjc800 GS_bjc880j GS_bjccmyk GS_bjccolor GS_bjcgray GS_bjcmono GS_bmp16 GS_bmp16m GS_bmp25
6 GS_bmp32b GS_bmpgray GS_bmpmono GS_bmpsep1 GS_bmpsep8 GS_ccr GS_cdeskjet GS_cdj1600 GS_cdj500 GS_cdj550 GS_cdj670 GS_cdj850 GS_cdj880 GS_cdj890 GS_cdj970
GS_cdjcolor GS_cdjmono GS_cdnj500 GS_cfax GS_chp2200 GS_cif GS_cljet5 GS_cljet5c GS_cljet5pr GS_coslw2p GS_coslwxl GS_cp50 GS_cups GS_declj250 GS_deskjet GS
_devicen GS_dfaxhigh GS_dfaxlow GS_display GS_dj505j GS_djet500 GS_djet500c GS_dl2100 GS_dmprt GS_dnj650c GS_epag GS_epl2050 GS_epl2050p GS_epl2120 GS_epl25
00 GS_epl2750 GS_epl5800 GS_epl5900 GS_epl6100 GS_eplcolor GS_eplmono GS_eps2write GS_eps9high GS_eps9mid GS_epson GS_epsonc GS_escpage GS_faxg3 GS_faxg32d
GS_faxg4 GS_fmlbp GS_fmpr GS_fs600 GS_gdi GS_hl1240 GS_hl1250 GS_hl7x0 GS_ibmpro GS_ijs GS_imagen GS_inferno GS_inkcov GS_iwhi GS_iwlo GS_iwlq GS_jetp3852 G
S_jj100 GS_jpeg GS_jpeggray GS_la50 GS_la70 GS_la75 GS_la75plus GS_laserjet GS_lbp310 GS_lbp320 GS_lbp8 GS_lex2050 GS_lex3200 GS_lex5700 GS_lex7000 GS_lips2
p GS_lips3 GS_lips4 GS_lips4v GS_lj250 GS_lj4dith GS_lj4dithp GS_lj5gray GS_lj5mono GS_ljet2p GS_ljet3 GS_ljet3d GS_ljet4 GS_ljet4d GS_ljet4pjl GS_ljetplus
GS_ln03 GS_lp1800 GS_lp1900 GS_lp2000 GS_lp2200 GS_lp2400 GS_lp2500 GS_lp2563 GS_lp3000c GS_lp7500 GS_lp7700 GS_lp7900 GS_lp8000 GS_lp8000c GS_lp8100 GS_lp8
200c GS_lp8300c GS_lp8300f GS_lp8400f GS_lp8500c GS_lp8600 GS_lp8600f GS_lp8700 GS_lp8800c GS_lp8900 GS_lp9000b GS_lp9000c GS_lp9100 GS_lp9300 GS_lp9400 GS_
lp9500c GS_lp9600 GS_lp9600s GS_lp9800c GS_lq850 GS_lvga256 GS_lxm3200 GS_lxm5700m GS_m8510 GS_mag16 GS_mag256 GS_md1xMono GS_md2k GS_md50Eco GS_md50Mono GS
_md5k GS_mgr4 GS_mgr8 GS_mgrgray2 GS_mgrgray4 GS_mgrgray8 GS_mgrmono GS_miff24 GS_mj500c GS_mj6000c GS_mj700v2c GS_mj8000c GS_ml600 GS_necp6 GS_npdl GS_oce9
050 GS_oki182 GS_oki4w GS_okiibm GS_omni GS_oprp GS_opvp GS_paintjet GS_pam GS_pbm GS_pbmraw GS_pcl3 GS_pcx16 GS_pcx24b GS_pcx256 GS_pcxcmyk GS_pcxgray GS_p
cxmono GS_pdfwrite GS_perm GS_pgm GS_pgmraw GS_pgnm GS_pgnmraw GS_photoex GS_picty180 GS_pj GS_pjetxl GS_pjxl GS_pjxl300 GS_pkm GS_pkmraw GS_pksm GS_pksmraw
 GS_plan GS_plan9bm GS_planc GS_plang GS_plank GS_planm GS_plib GS_plibc GS_plibg GS_plibk GS_plibm GS_png16 GS_png16m GS_png256 GS_pngalpha GS_pnggray GS_p
ngmono GS_pnm GS_pnmraw GS_ppm GS_ppmraw GS_pr1000 GS_pr1000_4 GS_pr150 GS_pr201 GS_ps2write GS_psdcmyk GS_psdrgb GS_pxlcolor GS_pxlmono GS_r4081 GS_rpdl GS
_sgirgb GS_sj48 GS_spotcmyk GS_st800 GS_stcolor GS_sunhmono GS_t4693d2 GS_t4693d4 GS_t4693d8 GS_tek4696 GS_tiff12nc GS_tiff24nc GS_tiff32nc GS_tiffcrle GS_t
iffg3 GS_tiffg32d GS_tiffg4 GS_tiffgray GS_tifflzw GS_tiffpack GS_tiffsep GS_uniprint GS_vgalib GS_xcf GS_xcfcmyk GS_xes ICONV```

**Comment by reezer** [comment] 2017-11-13 19:48
Correct. Getting the same one. Continuously.

Unsetting `CUPS`, but keeping `GS_cups` will lead to this behavior.

**Comment by bdrewery** [comment] 2017-11-14 01:15
Hm I cannot reproduce this.

**Comment by bdrewery** [comment] 2017-11-14 01:17
Can you please check your make.conf and /usr/local/etc/poudriere.d/*-options to see what selected options are being used? It would help to have a full build log for this package since it shows options near the top.

**Comment by brd** [comment] 2017-11-14 01:34
Probably: `print_ghostscript9-agpl-base_UNSET=	CUPS`

**Comment by reezer** [comment] 2017-11-14 18:17
Here a log of everything until the configure phase (cause pastebin is limited):
https://pastebin.com/cfzR3ZWa

**Comment by bdrewery** [comment] 2017-11-14 18:58
> Probably: `print_ghostscript9-agpl-base_UNSET= CUPS`

Ah yup. It's not a Poudriere bug then.

It's a bug in ports _Mk/bsd.options.mk_'s _SELECTED_OPTIONS_ change.

```
~/svn/ports/print/ghostscript9-agpl-base # grep UNSET /etc/make.conf
print_ghostscript9-agpl-base_UNSET= CUPS
# Added :tl to match on both GS_cups and CUPS
~/svn/ports/print/ghostscript9-agpl-base # make -V 'SELECTED_OPTIONS:tl:M*cup*'
gs_cups
# Using proper logic it does not appear
~/svn/ports/print/ghostscript9-agpl-base # make _SELECTED_OPTIONS='${ALL_OPTIONS:@opt@${PORT_OPTIONS:M${opt}}@} ${MULTI GROUP SINGLE RADIO:L:@otype@${OPTIONS_${otype}:@m@${OPTIONS_${otype}_${m}:@opt@${PORT_OPTIONS:M${opt}}@}@}@}' -V '_SELECTED_OPTIONS:tl:M*cup*'
```

I will fix in ports.

**Comment by bdrewery** [comment] 2017-11-14 19:01
Oh no it's actually due to _print/ghostscript9-agpl-base/files/Makefile.drivers_post_ messing with OPTIONS_UNSET after already including _Mk/bsd.port.options.mk_.
```
~/svn/ports/print/ghostscript9-agpl-base # make -V EMPTY
make: "/root/svn/ports/Mk/bsd.options.mk" line 303: here
make: "files/files/Makefile.drivers_post" line 63: here
```
So it's a bug in the port Makefile; it's not valid to mess with OPTIONS variables after including _bsd.port.options.mk_.

**Comment by bdrewery** [comment] 2017-11-14 19:03
Hmm well `make showconfig`, `make pretty-print-config` and the package all properly don't get _CUPS_ or _GS_cups_.  So I will move the _SELECTED_OPTIONS_ code to account for things like this.

**Comment by bdrewery** [comment] 2017-11-14 19:37
Fix in review at https://reviews.freebsd.org/D13092

**Comment by bdrewery** [comment] 2017-11-15 19:14
Fixed in ports _r454266_.

**Closed by bdrewery** 2017-11-15 19:14 UTC
Labels: Ports Bug
