### ISSUE TITLE
Provide support for passing build flags down the dependency chain

### ISSUE THREAD

**Issue by marcusva** [freebsd/poudriere#259] opened 2014-12-15 10:15 UTC
# Abstract

poudriere creates packages from ports in isolated jails, which feature their own set of environment variables that are usually set on starting the jail. A dependency X of a port Y thus is unaware of any environment settings the ports framework does on Y's behalf.
In some situations, it is necessary that environment settings are passed down the build chain to allow dependencies to build correctly based on whatever the framework decides "to be the best" for port Y.
# Problem Space

As of writing, the FreeBSD ports tree allows users and ports to build, install and use different versions of the Python language (`lang/python`) at the same time. Ports using the Python bits of the ports framework (namely `Mk/Uses/python.mk`) are enabled to choose a specific Python version or can be marked to support a series of Python versions, giving users (and other ports) the opportunity and flexibility to pick their specific preferred and supported version of the Python language.

The pre-pkg era did not allow ports to install packages for different Python versions, which used the same origin information, which was resolved with the availability of pkg 1.3. The ports and pkg framework are capable of installing e.g. py33-foo _and_ py27-foo originating from `devel/py-foo` at the same time.

A single poudriere instance however is unable to create such a set of packages. Within a single run, it can only create a package py33-foo _or_ py27-foo, but not both. This in turn limits the possibilities of creating different version-specific packages based on the same origin and won't allow different ports to refer to a shared dependency, which _would_ support those versions.
## Previous Workarounds

The limiting situation was resolved in the pre-pkg era by duplicating ports, renaming them and referring to either one of them within the specific consumers.

A port `py-onlypy33` may be limited to Python 3.3 and may depend on `py-foo`, which supports not only Python 3.3, but also Python 2.7. Another port `py-onlypy27`may also depend on `py-foo`, but only works with Python 2.7. This lead to the typical following workaround:
- Create port for py-foo, using Python 2.7
- Create port for py33-foo, using Python 3.3
- py-onlypy33 refers to py33-foo in the `BUILD_DEPENDS` or `RUN_DEPENDS`
- py-onlypy27 refers to py-foo in the `BUILD_DEPENDS` or `RUN_DEPENDS`
## Current Situation within the Ports

With pkg 1.3 and newer, a workaround as shown above is not necessary anymore. The Python bits of the ports framework allow ports to pass certain flags (specifically `DEPENDS_ARGS=PYTHON_VERSION=<versionnumber>`) to their dependencies, which can (re)act according to those. If a user wants to install `py-onlypy33`, the following will happen:
1. User executes `make install` for `py-onlypy33`
2. `python.mk` will append `PYTHON_VERSION=python3.3` to the `DEPENDS_ARGS`
3. ports framework traverses into the `py-foo`dependency
4. `python.mk` for `py-foo` notices `PYTHON_VERSION` and will instruct it to be built for Python 3.3
5. `py33-foo` is installed
6. `py-onlypy33` detects the proper `py33-foo` package and will continue to build and install

If the user is going to install `py-onlypy27`, the following will happen:
1. User executes `make install` for `py-onlypy27`
2. `python.mk` will append `PYTHON_VERSION=python2.7` to the `DEPENDS_ARGS`
3. ports framework traverses into the `py-foo`dependency
4. `python.mk` for `py-foo` notices `PYTHON_VERSION` and will instruct it to be built for Python 2.7
5. `py27-foo` is installed
6. `py-onlypy27` detects the proper `py27-foo` package and will continue to build and install
## Current Situation with Poudriere

Poudriere builds ports and their dependencies in (mostly) isolated jail environments, with the ability to parallelize builds. Information, such as the `DEPENDS_ARGS` from above are not shared or passed down the build chain. This results in the following behaviour for `py-onlypy33`:
1. poudriere gathers dependencies for `py-onlypy33`
2. poudriere runs the build for `py-foo` using the configured default python version (e.g. 2.7)
3. poudriere registers a package `py27-foo`
4. poudriere raises an error for `py-onlypy33` due to the unsatisfied dependency for `py33-foo`
# Solution

Poudriere needs to be able to pass around specific flags or settings, which can be set by a port or the ports framework. The ports framework may define a specific set of global variables, which should be respected by package builders (poudriere, tinderbox, etc.).

To prevent misbehaviour and to avoid limiting the parallelization features of package builders, those global variables should be available prior to any specific task for a port (`make fetch`, `make patch`, etc.), so that the internal package builder workflow may look like:
1. detect port
2. calculate global flags
3. gather dependencies to be built (with the global flags)
4. build dependencies (with the global flags)
5. build port

A single variable `PACKAGE_BUILD_FLAGS` may be sufficient and should be able to be passed down to dependencies of dependencies of dependencies of ...

**Comment by bdrewery** [comment] 2016-02-19 20:20
I'm taking another look at this. I noticed that even bsd.ruby.mk has the `DEPENDS_ARGS`. I misunderstood some the changes that were made leading up to this problem.

**Comment by bdrewery** [comment] 2016-02-19 20:26
Caching `DEPENDS_ARGS` per port and passing it to their dependencies may discover new packages that need to be built.

If we get dependencies B and C from PortA and dependencies C and D from PortB, we need to lookup further dependencies given the tuples B:PortA_DEPENDS_ARGS, C:PortA_DEPENDS_ARGS, C:PortB_DEPENDS_ARGS, and D:PortB_DEPENDS_ARGS. The DEPENDS_ARGS may all match so there would only be 1 actual lookup, but if they don't then we can discover new PKGNAMES from those lookups to queue. It could end up with A B C D, or A B B-II C C-II D.

I think implementing that makes sense and would solve this.

The problem then is that it's not easy with the current code (especially to keep performance acceptable for 24000 port build startups) but I do consider it a bug and in need of fixing.

**Comment by bdrewery** [comment] 2016-02-19 20:27
And those `DEPENDS_ARGS` for the generated package would have to be passed into the actual build of it as well of course.

**Comment by bdrewery** [comment] 2016-02-19 20:48
I think to fix this and set us up for the future of sub-packages, everything tracking an origin needs to instead track a "package" object which has stuff like the `DEPENDS_ARGS` and the origin it came from for the sake of building. The queue is already all pkgname-oriented at least.

**Comment by bdrewery** [comment] 2016-02-19 20:52
<pre>
dns/unbound/Makefile:DEPENDS_ARGS+=     WITH_GOST=yes
dns/unbound/Makefile:DEPENDS_ARGS+=     WITH_ECDSA=yes
</pre>

These are wrong since we don't generally support multiple packages installed at once but the plan with Poudriere will allow supporting something like this in the future perhaps.

**Comment by bdrewery** [comment] 2016-06-08 19:39
@bapt 's comment on this is that the queue should track `origin:key=vaue:key2=value` which would be an extensible format to support variants and other features in the future.

**Comment by bdrewery** [comment] 2016-06-23 22:34
There's 2 implementations that tackle this problem.

https://github.com/bbqsrc/poudriere/commit/73dfbc4a88b79ca2288c0732522e04f38eabdcd8 and https://github.com/freebsd/poudriere/pull/314

**Comment by bdrewery** [comment] 2016-06-24 02:19
I have a PoC for this working.

<pre>
testport net/tiny-network-utilities

Current:
[00:00:08] ====>> Debug: net/tiny-network-utilities |  depends on net/py-netifaces
[00:00:08] ====>> Debug: net/tiny-network-utilities |  depends on textproc/py-hexdump
[00:00:09] ====>> Debug: net/py-netifaces depends on lang/python27
[00:00:09] ====>> Debug: net/py-netifaces depends on devel/py-setuptools27
[00:00:09] ====>> Debug: devel/py-setuptools27 depends on lang/python27
[00:00:09] ====>> Debug: textproc/py-hexdump depends on devel/py-setuptools27
[00:00:09] ====>> Debug: textproc/py-hexdump depends on lang/python27

Fixed:
[00:00:08] ====>> Debug: net/tiny-network-utilities | tiny-network-utilities-0.150519 depends on net/py-netifaces
[00:00:08] ====>> Debug: net/tiny-network-utilities | tiny-network-utilities-0.150519 depends on textproc/py-hexdump
[00:00:10] ====>> Debug: net/py-netifaces | py34-netifaces-0.10.4 depends on lang/python34 | python34-3.4.4_2
[00:00:10] ====>> Debug: net/py-netifaces | py34-netifaces-0.10.4 depends on devel/py-setuptools34 | py34-setuptools34-20.0
[00:00:10] ====>> Debug: textproc/py-hexdump | py34-hexdump-3.3 depends on devel/py-setuptools34 | py34-setuptools34-20.0
[00:00:10] ====>> Debug: textproc/py-hexdump | py34-hexdump-3.3 depends on lang/python34 | python34-3.4.4_2
</pre>

There's several challenges to fix still. One is that for `bulk -a` we optimize the queue by assuming that we will visit all origins once when looking up dependencies and thus don't do recursive dependency lookup.  That optimization will have to come out to make this work properly.  That could seriously hurt the package build times on the cluster.  So I need to come up with more optimizations for it.

Another challenge is the `TRIM_ORPHANED_BUILD_DEPS` feature which only works off of origins.  This feature is enabled by default since it is an optimization to avoid building something unneeded.

What I've done is make a 2-tuple of `ORIGIN:DEPENDS_ARGS` to map to a particular `PKGNAME`.  For the `VARIANTS` feature I would just need to add in the `VARIANT` as well. It's not too bad to extend for that, but I suspect that the proper `VARIANTS` implementation should be using `DEPENDS_ARGS` anyhow, so there may be nothing that needs to be extended.

**Comment by bdrewery** [comment] 2016-06-24 02:22
Actually I will just add in a `VARIANT` now to the tuple.  While a port may need to pass its `VARIANT` in `DEPENDS_ARGS`, the port itself relies on a particular `VARIANT` to determine its `PKGNAME`.  So it does need to go into the set.

**Comment by bdrewery** [comment] 2016-06-27 17:18
This may also break some ports.

Example at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=195342 with fix at https://bz-attachments.freebsd.org/attachment.cgi?id=150142

**Comment by johnramsden** [comment] 2017-06-06 06:23
Is there an alternative for the meantime? I'm trying to build `sysutils/py3-iocage`, which requires Python 3.6 and I keep getting the following. Not sure what I should do.

```
[00:00:06] ====>> [01][00:00:00] Starting build of www/py3-requests
[00:00:11] ====>> [01][00:00:05] Finished build of www/py3-requests: Failed: run-depends
[00:00:11] ====>> [01][00:00:05] Skipping build of sysutils/py3-iocage: Dependent port www/py3-requests failed
```

**Comment by koobs** [comment] 2017-06-06 09:17
@johnramsden If your tree is up to date, this is an issue with the latest py-requests commit, which requires py-chardet >= 3.0.2, but the py3-chardet port doesn't inherit its PORTVERSION from the py-chardet port (it should be a slave port). I'm on it

**Comment by johnramsden** [comment] 2017-06-06 22:46
@koobs Yeah, my tree is up to date. Is there anything I need to do, or are you saying I just need to wait for an update to py3-chardet.

**Comment by woodsb02** [comment] 2017-06-06 23:37
@koobs has fixed it. Try updating your ports once again

**Comment by woodsb02** [comment] 2017-06-07 00:03
See https://svnweb.freebsd.org/changeset/ports/442754

**Comment by johnramsden** [comment] 2017-06-07 00:41
@woodsb02 So i updated again, no change.

```
root@poudriere:/usr/home/john # poudriere jail -u -j 11amd64
[00:00:00] ====>> Upgrading using ftp
/etc/resolv.conf -> /usr/local/poudriere/jails/11amd64/etc/resolv.conf
mount: /usr/local/poudriere/jails/11amd64/compat: No such file or directory
Looking up update.FreeBSD.org mirrors... 4 mirrors found.
Fetching metadata signature for 11.0-RELEASE from update6.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.

No updates needed to update system to 11.0-RELEASE-p10.
No updates are available to install.
Run '/usr/sbin/freebsd-update.fixed fetch' first.
11.0-RELEASE-p10
[00:00:25] ====>> Recording filesystem state for clean... done


root@poudriere:/usr/home/john # poudriere ports -u -p HEAD
[00:00:00] ====>> Updating portstree "HEAD"
Looking up portsnap.FreeBSD.org mirrors... 6 mirrors found.
Fetching snapshot tag from your-org.portsnap.freebsd.org... done.
Ports tree hasn't changed since last snapshot.
No updates needed.
Ports tree is already up to date.


root@poudriere:/usr/home/john # poudriere options -j 11amd64 -p HEAD -f /usr/local/etc/poudriere.d/port-list-iocage
[00:00:00] ====>> Appending to make.conf: /usr/local/etc/poudriere.d/11amd64-make.conf
===> Setting user-specified options for py36-iocage-0.9.8.1 and dependencies


root@poudriere:/usr/home/john # poudriere bulk -j 11amd64 -p HEAD -f /usr/local/etc/poudriere.d/port-list-iocage
[00:00:00] ====>> Creating the reference jail... done
[00:00:00] ====>> Mounting system devices for 11amd64-HEAD
[00:00:00] ====>> Mounting ports/packages/distfiles
[00:00:00] ====>> Stashing existing package repository
[00:00:00] ====>> Mounting packages from: /usr/local/poudriere/data/packages/11amd64-HEAD
[00:00:00] ====>> Copying /var/db/ports from: /usr/local/etc/poudriere.d/11amd64-options
[00:00:00] ====>> Appending to make.conf: /usr/local/etc/poudriere.d/11amd64-make.conf
/etc/resolv.conf -> /usr/local/poudriere/data/.m/11amd64-HEAD/ref/etc/resolv.conf
[00:00:00] ====>> Starting jail 11amd64-HEAD
[00:00:00] ====>> Logs: /usr/local/poudriere/data/logs/bulk/11amd64-HEAD/2017-06-06_10h34m22s
[00:00:00] ====>> WWW: http://poudriere.ramsden.network//build.html?mastername=11amd64-HEAD&build=2017-06-06_10h34m22s
[00:00:00] ====>> Loading MOVED
[00:00:01] ====>> Calculating ports order and dependencies
[00:00:03] ====>> Sanity checking the repository
[00:00:03] ====>> Checking packages for incremental rebuild needed
[00:00:05] ====>> Deleting stale symlinks
[00:00:05] ====>> Deleting empty directories
[00:00:05] ====>> Cleaning the build queue
[00:00:05] ====>> Recording filesystem state for prepkg... done
[00:00:05] ====>> Building 2 packages using 2 builders
[00:00:05] ====>> Starting/Cloning builders
[00:00:06] ====>> Hit CTRL+t at any time to see build progress and stats
[00:00:06] ====>> [01][00:00:00] Starting build of www/py3-requests
[00:00:10] ====>> [01][00:00:04] Finished build of www/py3-requests: Failed: run-depends
[00:00:11] ====>> [01][00:00:05] Skipping build of sysutils/py3-iocage: Dependent port www/py3-requests failed
[00:00:11] ====>> Stopping 2 builders
[00:00:11] ====>> No package built, no need to update the repository
[00:00:11] ====>> Committing packages to repository
[00:00:11] ====>> Removing old packages
[00:00:11] ====>> Failed ports: www/py3-requests:run-depends
[00:00:11] ====>> Skipped ports: sysutils/py3-iocage
[11amd64-HEAD] [2017-06-06_10h34m22s] [committing:] Queued: 2  Built: 0  Failed: 1  Skipped: 1  Ignored: 0  Tobuild: 0   Time: 00:00:12
[00:00:11] ====>> Logs: /usr/local/poudriere/data/logs/bulk/11amd64-HEAD/2017-06-06_10h34m22s
[00:00:11] ====>> WWW: http://poudriere.ramsden.network//build.html?mastername=11amd64-HEAD&build=2017-06-06_10h34m22s
[00:00:11] ====>> Cleaning up
[00:00:11] ====>> Unmounting file systems
```

**Comment by koobs** [comment] 2017-06-07 03:25
@johnramsden @woodsb02  It's failing for another dependency now (py3-idna, you can see by trying to build py3-requests), but this is the wrong place to go over this in detail (freenode irc or bugzilla is better)

Can everyone clean up (delete)  their comments please

**Comment by bdrewery** [comment] 2017-06-13 13:33
There's an actual patch to resolve this and to take it a step further to support `FLAVORS` in #483.  Note the problem is fixed in that PR even without `FLAVORS`; `FLAVORS` is just the next step.

**Closed** 2017-06-16 01:01 UTC
Labels: bug, Feature_Request, Flavors

**Comment by bdrewery** [comment] 2022-11-08 23:06
6ce2d0b58733ea86df26668a98e0ad356c1a6318 dropped this support. `FLAVORS` is the replacement.
