### ISSUE TITLE
Add support for `make test` to testport

### ISSUE THREAD

**Issue by DragonSA** [freebsd/poudriere#377] opened 2016-02-23 18:00 UTC
With the official support of `make test` in FreeBSD's Ports tree, and the corresponding TEST_DEPENDS it would be most useful if this target was run after packaging and QA.

**Comment by mat813** [comment] 2016-02-23 21:55
There is a patch for it, #355, but there's a problem with recursive dependencies in TEST_DEPENDS.
I think the best way to handle it is to only run the test target when running testport, but not when running bulk -t.

**Comment by bdrewery** [comment] 2016-02-23 23:42
That would leave `testport` broken sometimes.

Closing as duplicate of #355.

**Closed by bdrewery** 2016-02-23 23:42 UTC
