### ISSUE TITLE
Cache jail installation files for all non-src based (or binary based) -m <method>'s

### ISSUE THREAD

**Issue by koobs** [freebsd/poudriere#271] opened 2015-01-28 12:52 UTC
Would help save bandwidth & time, especially when trying to reproduce/debug jail based errors / environments where you want a clean environment every time.

Potentially made optional (opt-in) for jail -c calls with a new arg (-C ?)

**Comment by so14k** [comment] 2015-01-28 14:14
Good idea.

**Comment by bdrewery** [comment] 2017-06-14 16:56
This can possibly be mitigated by using a caching proxy and `FTP_PROXY` / `HTTP_PROXY`.

**Comment by bdrewery** [comment] 2017-06-14 17:47
Duplicate of #137

**Closed by bdrewery** 2017-06-14 17:47 UTC
Labels: Feature_Request
