### ISSUE TITLE
Unable to create jail using pkgbase method

### ISSUE THREAD

**Issue by rbgarga** [freebsd/poudriere#1088] opened 2023-11-13 15:42 UTC
## Prerequisites
- [x] Have you checked for an existing issue describing your problem?
- [x] Are you running the latest version?
- [x] Is your ports tree recent?
- [x] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
Unable to create jail using pkgbase method

## How to reproduce
Just run
```
poudriere jail -c -j test-pkgbase -m pkgbase=http://pkg.freebsd.org -v 15
```

## Expected behavior
It should create a FreeBSD 15 jail using pkgbase repository published at https://pkg.freebsd.org/FreeBSD:15:amd64/

## Environment
 - Host OS [e.g. 12.2 amd64]: 15-CURRENT main-n266355-cb57f50e640 amd64
 - Jail OS [e.g. 12.0 powerpc]: 15-CURRENT amd64
 - Poudriere Version [e.g. 3.3.1 or git hash or port version]: poudriere-devel-3.4.99.20231030

**Comment by igalic** [comment] 2023-12-23 17:29
can you try the full URL, https://pkg.freebsd.org/FreeBSD:15:amd64/base_latest/  ?

**Comment by rbgarga** [comment] 2023-12-26 11:24
> can you try the full URL, https://pkg.freebsd.org/FreeBSD:15:amd64/base_latest/ ?

this way?

```
# poudriere jail -c -j test -m pkgbase=https://pkg.freebsd.org/FreeBSD:15:amd64/base_latest -v main
[00:00:00] Creating test fs at /usr/local/poudriere/jails/test... done
[00:00:00] Installing main amd64 from https://pkg.freebsd.org/FreeBSD:15:amd64/base_latest ...Updating pkgbase repository catalogue...
pkg: An error occured while fetching package
pkg: An error occured while fetching package
repository pkgbase has no meta file, using default settings
pkg: An error occured while fetching package
pkg: An error occured while fetching package
Unable to update repository pkgbase
Error updating repositories!
Updating pkgbase repository catalogue...
pkg: An error occured while fetching package
pkg: An error occured while fetching package
repository pkgbase has no meta file, using default settings
pkg: An error occured while fetching package
pkg: An error occured while fetching package
Unable to update repository pkgbase
Error updating repositories!
[00:00:02] Recording filesystem state for clean... done
[00:00:02] Jail test main amd64 is ready to be used
```

**Comment by grahamperrin** [comment] 2024-02-09 01:41
From the commit log message for <https://github.com/freebsd/poudriere/commit/4568e0c8cd7d04f485443293f799f7b9ad014f49>: 

> `poudriere -c -j pkgbase=http://example.com/pkgbase -a amd64 -v 14`

That's expected to fail, here's a record of me stumbling with an attempt to create a 15.0-CURRENT jail. 

```text
root@mowa219-gjp4-zbook-freebsd:~ # poudriere -c -j pkgbase=https://pkg.freebsd.org/pkgbase -a amd64 -v 15
Illegal option -c
Usage: poudriere [-ANv] [-e etcdir] command [options]

…
root@mowa219-gjp4-zbook-freebsd:~ # poudriere jail -c -j pkgbase=https://pkg.freebsd.org/pkgbase -a amd64 -v 15
[00:00:00] Error: The jailname cannot contain a period (.). See jail(8)
root@mowa219-gjp4-zbook-freebsd:~ # poudriere jail -c -j main pkgbase=https://pkg.freebsd.org/pkgbase -a amd64 -v 15
Missing: VERSION
poudriere jail [parameters] [options]

…
root@mowa219-gjp4-zbook-freebsd:~ # poudriere jail -c -j main pkgbase=https://pkg.freebsd.org/pkgbase -a amd64 -v 15.0-CURRENT
Missing: VERSION
poudriere jail [parameters] [options]

…
root@mowa219-gjp4-zbook-freebsd:~ # poudriere jail -c -j main -m pkgbase=https://pkg.freebsd.org/pkgbase -a amd64 -v 15
[00:00:00] Creating main fs at /usr/local/poudriere/jails/main... done
[00:00:00] Installing 15 amd64 from https://pkg.freebsd.org/pkgbase ...Updating pkgbase repository catalogue...
pkg: An error occured while fetching package
pkg: An error occured while fetching package
repository pkgbase has no meta file, using default settings
pkg: An error occured while fetching package
pkg: An error occured while fetching package
Unable to update repository pkgbase
Error updating repositories!
Updating pkgbase repository catalogue...
pkg: An error occured while fetching package
pkg: An error occured while fetching package
repository pkgbase has no meta file, using default settings
pkg: An error occured while fetching package
pkg: An error occured while fetching package
Unable to update repository pkgbase
Error updating repositories!
[00:00:02] Recording filesystem state for clean... done
[00:00:02] Jail main 15 amd64 is ready to be used
root@mowa219-gjp4-zbook-freebsd:~ # poudriere jail -l
JAILNAME VERSION ARCH  METHOD  TIMESTAMP           PATH
main     15      amd64 pkgbase 2024-02-09 01:26:45 /usr/local/poudriere/jails/main
root@mowa219-gjp4-zbook-freebsd:~ # poudriere jail -u -j main
[00:00:00] Upgrading using pkgbase
Updating FreeBSD-ports repository catalogue...
Fetching meta.conf: 100%    163 B   0.2kB/s    00:01    
Fetching packagesite.pkg: 100%    7 MiB   7.4MB/s    00:01    
pkg: Error opening the trusted directory /usr/share/keys/pkg/trusted
pkg: Error loading trusted certificates
Unable to update repository FreeBSD-ports
Updating FreeBSD-base repository catalogue...
Fetching meta.conf: 100%    163 B   0.2kB/s    00:01    
Fetching packagesite.pkg: 100%   40 KiB  41.0kB/s    00:01    
pkg: Error opening the trusted directory /usr/share/keys/pkg/trusted
pkg: Error loading trusted certificates
Unable to update repository FreeBSD-base
Updating poudriere repository catalogue...
Fetching meta.conf: 100%    163 B   0.2kB/s    00:01    
Fetching packagesite.pkg: 100%   41 KiB  42.4kB/s    00:01    
Processing entries: 100%
poudriere repository update completed. 146 packages processed.
Error updating repositories!
[00:00:04] Error: pkg update failed
root@mowa219-gjp4-zbook-freebsd:~ # file /usr/share/keys/pkg/trusted
/usr/share/keys/pkg/trusted: directory
root@mowa219-gjp4-zbook-freebsd:~ # du -hs /usr/share/keys/pkg/trusted
1.0K    /usr/share/keys/pkg/trusted
root@mowa219-gjp4-zbook-freebsd:~ # ls -hln /usr/share/keys/pkg/trusted
total 1
-rw-r--r--  1 0 0  100B Feb  7 20:14 pkg.freebsd.org.2013102301
root@mowa219-gjp4-zbook-freebsd:~ # 
```

The tail end of what's above _might_ include something of interest. 

----

```text
root@mowa219-gjp4-zbook-freebsd:~ # uname -aKU ; pkg iinfo poudriere-devel
FreeBSD mowa219-gjp4-zbook-freebsd 15.0-CURRENT FreeBSD 15.0-CURRENT main-n268104-d04abb05375d GENERIC-NODEBUG amd64 1500013 1500013
poudriere-devel-3.4.99.20240122
root@mowa219-gjp4-zbook-freebsd:~ # pkg -vv | grep -e url -e enabled -e priority
    url             : "http://pkg0.fra.freebsd.org/FreeBSD:15:amd64/latest",
    enabled         : yes,
    priority        : 2,
    url             : "pkg+https://pkg.freebsd.org/FreeBSD:15:amd64/base_latest",
    enabled         : yes,
    priority        : 0,
    url             : "file:///usr/local/poudriere/data/packages/main-default",
    enabled         : yes,
    priority        : 3
root@mowa219-gjp4-zbook-freebsd:~ # 
```

Maybe relevant: my `/etc/pkg/FreeBSD.conf` is modified to use a non-standard name `FreeBSD-ports` (for packages of FreeBSD ports).

**Comment by grahamperrin** [comment] 2024-02-09 01:48
Experimenting with http (in lieu of https) and quotation marks: 

```text
root@mowa219-gjp4-zbook-freebsd:~ # poudriere -v jail -c -j main -m pkgbase="http://pkg.freebsd.org/FreeBSD:15:amd64/base_latest/" -a amd64 -v 15
[00:00:00] Creating main fs at /usr/local/poudriere/jails/main... done
[00:00:01] Installing 15 amd64 from http://pkg.freebsd.org/FreeBSD:15:amd64/base_latest/ ...Updating pkgbase repository catalogue...
pkg: An error occured while fetching package
pkg: An error occured while fetching package
repository pkgbase has no meta file, using default settings
pkg: An error occured while fetching package
pkg: An error occured while fetching package
Unable to update repository pkgbase
Error updating repositories!
Updating pkgbase repository catalogue...
pkg: An error occured while fetching package
pkg: An error occured while fetching package
repository pkgbase has no meta file, using default settings
pkg: An error occured while fetching package
pkg: An error occured while fetching package
Unable to update repository pkgbase
Error updating repositories!
[00:00:02] Recording filesystem state for clean... done
[00:00:02] Jail main 15 amd64 is ready to be used
root@mowa219-gjp4-zbook-freebsd:~ # poudriere jail -d -j main
[00:00:00] Are you sure you want to delete the jail? [y/N] y
[00:00:01] Removing main jail... done
[00:00:03] Cleaning main data... done
root@mowa219-gjp4-zbook-freebsd:~ # 
```

**Comment by grahamperrin** [comment] 2024-03-26 01:29
From <https://lists.freebsd.org/archives/freebsd-pkgbase/2024-March/000353.html>: 

> i believe this issue is because pkg.freebsd.org puts the packages in `base_latest`, while poudriere expects them to be in `latest`. …

**Comment by bdrewery** [comment] 2024-04-19 19:05
Dupe of #1137 where the fixes are linked. The new syntax is `-m pkgbase=base_latest -U https://pkg.freebsd.org/pkgbase`

**Closed by bdrewery** 2024-04-19 19:05 UTC
Labels: bug
