### ISSUE TITLE
Option to force building a package

### ISSUE THREAD

**Issue by ntinti** [freebsd/poudriere#602] opened 2018-03-06 09:24 UTC
It would be nice to have the possibility to build a package  even if poudriere thinks it is not necessary. If I change a make.conf poudriere perhaps does not recognize this change and do nothing. E.g. such configuration:
```
.if ${.CURDIR:M*/ports*/www/elog}
WWWOWN=elog
WWWGRP=elog
.endif
.if ${.CURDIR:M*/ports*/www/dokuwiki}
WWWOWN=www
WWWGRP=www
.endif
```

**Comment by bdrewery** [comment] 2018-03-06 18:13
That seems like an obscure case that Poudriere should auto detect, hmm.

**Comment by ntinti** [comment] 2018-03-06 19:18
Im not a developer but an administrator. I want to replace portupgrade and marry the best of the worlds: Ports and Packages. Therefore I build our own repository server for server and services. Want more 'obscure' ;-)? 
Build several PHP versions parallel on the same server:
```
PHP_ALT=php56 php70 php71 php72
.for port in ${PHP_ALT}
.if ${.CURDIR:M*/ports*/lang/${port}}
DISABLE_CONFLICTS=YES
PREFIX=/usr/local/${port}
PHPBASE=/usr/local/${port}
LOCALBASE=/usr/local
CONFIGURE_ARGS+=--datadir=/usr/local/${port}/share
CONFIGURE_ARGS+=--bindir=/usr/local/${port}/bin
CONFIGURE_ARGS+=--with-config-file-scan-dir=/usr/local/${port}/etc/php
.endif
.endfor
```

**Comment by bdrewery** [comment] 2018-03-06 19:49
Yup that's fine, I've done similar things with other ports.
All I meant by obscure is that Poudriere has a list of things it checks for to handle incremental rebuilds. `USER` and `GROUP` were not one.
This bug is actually similar to #310 which you've commented on. I'm not sure if Poudriere really should be checking every little thing as normally if a committer modifies these values they should bump `PORTREVISION`, and a user should if they are hacking around in make.conf like this too. So I think resolving #310 may be better than making Poudriere even more "smart".  That "smart" causes us a lot of other problems because it rebuilds things far too aggressively.

**Comment by bdrewery** [comment] 2018-03-06 19:50
I've often had to bump `PORTREVISION` myself in ports to work around problems like this. I almost think we need ` USERREVISION` for customizations like this but it's unlikely to be implemented in Ports/Pkg.

**Comment by brd** [comment] 2018-03-06 22:16
@bdrewery I have just used `find /usr/local/poudriere/data/packages -name foo\* -delete` because it felt cleaner than polluting PORTREVISION to me personally.  (just another data point..)

**Comment by bdrewery** [comment] 2018-03-07 00:35
Same here.

**Comment by bdrewery** [comment] 2018-03-07 00:35
But then I have to remember to `pkg install -f` downstream.

**Comment by ntinti** [comment] 2018-03-08 08:22
OK. Thanks a lot. I will work with `PORTREVISION` if I need an update that's not automatically build. And to make poudriere "smarter" I can make my own shell scripts or will it be an idea if you start a scripts and snippets collection in your wiki?

**Comment by bdrewery** [comment] 2019-03-05 01:22
Dupe of #310

**Closed by bdrewery** 2019-03-05 01:22 UTC
